# C# - Backend - CD

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'joachimveulemans/chessgame'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'backend'
